apiVersion: apps/v1
kind: Deployment
metadata:
  name: personalinfo-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      personalinfo: web
  template:
    metadata:
      labels:
        personalinfo: web
    spec:
      containers:
      - name: personalinfo-site
        image: shahcoding/personalinfo:1.0
